name: Puppet Litmus Tests with matrix_from_metadata_v3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_matrix_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Install matrix_from_metadata_v3
        run: gem install puppet_litmus

      - name: Generate GitHub Action Matrix
        run: |
          bundle exec matrix_from_metadata_v3 --output github --runner ubuntu-latest > matrix.json
          echo "MATRIX=$(cat matrix.json)" >> $GITHUB_ENV

  litmus_tests:
    needs: generate_matrix_and_test
    runs-on: ubuntu-latest
    
    strategy:
      matrix: ${{ fromJson(env.MATRIX) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Install Puppet Litmus
        run: gem install puppet_litmus

      - name: Provision Test Environment
        run: bundle exec rake 'litmus:provision[docker]'
        env:
          TARGET_HOSTS: "${{ matrix.platform }}"

      - name: Install Puppet Agent
        run: bundle exec rake 'litmus:install_agent'
        env:
          TARGET_HOSTS: "${{ matrix.platform }}"

      - name: Install Module
        run: bundle exec rake 'litmus:install_module'
        env:
          TARGET_HOSTS: "${{ matrix.platform }}"

      - name: Run Acceptance Tests
        run: bundle exec rake 'litmus:acceptance:parallel'
        env:
          TARGET_HOSTS: "${{ matrix.platform }}"

      - name: Tear Down Environment
        if: always()
        run: bundle exec rake 'litmus:tear_down'
        env:
          TARGET_HOSTS: "${{ matrix.platform }}"
