name: Puppet Litmus Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Generate matrix
        id: set-matrix
        run: |
          MATRIX_OUTPUT=$(bundle exec matrix_from_metadata_v3 --output github)
          echo "matrix=${MATRIX_OUTPUT}" >> $GITHUB_OUTPUT

  run-tests:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5.x'
      - name: Install dependencies
        run: |
          bundle install
      - name: Provisioning
        run: bundle exec rake litmus:provision_list[${{ matrix.platform }}]
      - name: Install Puppet agent
        run: bundle exec rake litmus:install_agent
      - name: Install module and dependencies
        run: bundle exec rake litmus:install_module
      - name: Run acceptance tests
        run: bundle exec rake litmus:acceptance:parallel
