name: Generate and Use Test Matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}  # Declare matrix output for the job
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Generate matrix from metadata
      id: generate-matrix  # Set ID to use the output later
      run: |
        # Generate the matrix and write output to matrix_output.log
        bundle exec matrix_from_metadata_v3 \
          --platform-exclude 'RedHat-(7|8|9)' \
          --platform-exclude 'SLES-(12|15)' \
          --platform-exclude 'Windows-(10|2012 R2|2016|2019)' \
          --output auto > matrix_output.log

        # Extract the matrix part from the output and set it as an output
        matrix=$(jq -c '.matrix' matrix_output.log)
        echo "matrix=$matrix" >> $GITHUB_OUTPUT

    - name: Debug output
      run: cat matrix_output.log

  use-matrix:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build.outputs.matrix) }}  # Use the matrix output from the build job
    steps:
    - uses: actions/checkout@v3
    - name: Use Matrix
      run: echo "Running on ${{ matrix.label }}
