name: Generate Test Matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Generate matrix from metadata
      run: |
        ruby matrix_from_metadata_v3 > matrix.json
    - name: Set the matrix output
      id: set-matrix
      run: echo "::set-output name=matrix::$(cat matrix.json)"

  use-matrix:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v3

    - name: Use Matrix
      run: echo "Running on ${{ matrix.label }}"
