name: Generate Test Matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Specify the Ruby version you need

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Generate matrix from metadata
      run: bundle exec matrix_from_metadata_v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Print matrix results
      run: cat matrix.json  # Adjust based on how your script outputs results
