name: Generate Test Matrix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}  # Declare output for the job
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Specify the Ruby version you need

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Generate matrix from metadata
      run: bundle exec matrix_from_metadata_v3 --output github > matrix.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set the matrix output
      id: set-matrix
      run: echo "{matrix}={matrix.json}" >> $GITHUB_OUTPUT
  use-matrix:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.build.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v3

    - name: Use Matrix
      run: echo "Running on ${{ matrix.label }}"
